name: initial workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: hello world
      run: echo "hello world"

  goodbye:
    runs-on: ubuntu-latest
    steps:
    - name: goodbye wolrd
      run: echo "goodbye world"